server:
  port: 8081

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/expense-db
    username: admin
    password: password
    hikari:
      poolName: Hikari
      auto-commit: false
  sql:
    init:
      continue-on-error: true
      mode: always

# Swagger/OpenAPI configurations
springdoc:
  swagger-ui:
    oauth:
      client-secret: internal

# CORS Configurations
app:
  allowed-api-origin: http://localhost:4200,http://localhost:4201
